name: API
on: [push]
jobs:
  Api-Tests:
      name: Run api-tests
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repository
          uses: actions/checkout@v2
        - name: Set up node
          uses: actions/setup-node@v1
          with:
            node-version: '14.x'
        - run: npm install -g newman
        - run: npm run newman

  slackNotification:
    needs: Api-Tests
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}