name: API
on: [push]
jobs:
  Api-Tests:
      name: Run api-tests
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repository
          uses: actions/checkout@v2
        - name: Set up node
          uses: actions/setup-node@v1
          with:
            node-version: '14.x'
        - run: npm install -g newman
        - run: npm run newman